<table class="table table-striped-columns">
<thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Marca</th>
      <th scope="col">Precio</th>
      <th scope="col">Color</th>
      <th scope="col">Categoria</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <th scope="row"> <?= $fila->id ?> </th>
        <td> <?= $fila->marca ?> </td>
        <td> <?= $fila->precio ?> </td>
        <td> <?= $fila->color ?> </td>
        <td> <?= $fila->id_periferico ?> </td>
    </tr>
  </tbody>
</table>