<!-- formulario para agregar categoria -->

<form action="agregarCategoria" method="POST" class="my-4">
    <div class="row text-center">
        <div class="col-3">
            <div class="form-group">
                <label>Categoria</label>
                <input name="categoria" type="text" class="form-control">
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Agregar</button>
</form>